#!/bin/bash
# playcdt: script bash to play TZX/CDT tape images of Amstrad CPC & ZX Spectrum
# requires playtzx and audacious (see http://malagaoriginal.blogspot.com.es)
# version 0.1 alpha - GNU/GPL 2 Jesus Basco 2016
es_zip=$(file -b "$1" | grep -i zip | wc -l)
es_tzx=$(file -b "$1" | grep -i tzx | wc -l)
tmptzx=/tmp
if [ $# -ne 1 ]; then
   echo "ERROR: Hay que poner el archivo TZX/CDT"
   exit -1
fi
if [ -f "$1" ]; then
   if [ $es_tzx == 1 ]; then
      echo Reproduciendo archivo \""$1"\"
      playtzx -voc "$1" $tmptzx/temporal.voc
      audacious -pqH $tmptzx/temporal.voc
      rm $tmptzx/temporal.voc
   elif [ $es_zip == 1 ]; then
      echo AVISO: El archivo \""$1"\" es un archivo ZIP... descomprimiendo e intentando sacar un archivo CDT/TZX
      mkdir -p $tmptzx/tzxtmp
      unzip -C "$1" -d $tmptzx/tzxtmp
      for i in `ls $tmptzx/tzxtmp/*.{tzx,cdt}`;
      do
          playcdt "$i"
      done
      rm -rf $tmptzx/tzxtmp
      exit
   else
      echo ERROR: El archivo \""$1"\" no es un CDT/TZX
   fi
else
   echo ERROR: El archivo \""$1"\" no existe
   exit -1
fi
